// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SistemaMVCOracle.Data;

#nullable disable

namespace SistemaMVCOracle.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaMVCOracle.Models.Producto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("FECHA_REGISTRO")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("NOMBRE")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("PRECIO")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int>("STOCK")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ID");

                    b.ToTable("PRODUCTOS_O");
                });
#pragma warning restore 612, 618
        }
    }
}
